name: cooljeanius/gvpe-2.25
on:
  push:
    branches:
    - "**/*"
  pull_request:
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
#     # 'Transformers::TravisCI::Scripts::Dependencies' dependencies are currently unsupported
#     # 'compiler' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: sudo apt-get install texinfo
    - run: "./configure && make && make check"
    strategy:
      matrix:
        compiler:
        - clang
        - gcc
