name: cooljeanius/gvpe-2.25
on:
  push:
    branches:
    - "**/*"
  pull_request:
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.1
#     # 'Transformers::TravisCI::Scripts::Dependencies' dependencies are currently unsupported
#     # 'compiler' was not transformed because there is no suitable equivalent in GitHub Actions
    - name: Dependencies
      run: sudo apt-get update && sudo apt-get install texinfo
    - name: Configure
      run: ./configure
    - name: Build
      run: make
    - name: Test
      run: make check && make distcheck
    strategy:
      fail-fast: false
      matrix:
        compiler:
        - clang
        - gcc
